# compose.nginx.yml 1.3
networks:
  shared-network:
    external: true

services:
  nginx-proxy:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
      - "${TOSCANA_HTTPS_PORT}:8443"
      - "${FLEXORA_HTTPS_PORT}:8444"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx/conf.d/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
      - nginx_logs:/var/log/nginx
      - nginx_cache:/var/cache/nginx
    environment:
      server_hostname: ${SERVER_HOSTNAME}
      toscana_https_port: ${TOSCANA_HTTPS_PORT}
      flexora_https_port: ${FLEXORA_HTTPS_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
      # Versione semplificata senza controllo servizi
    entrypoint: >
      /bin/sh -c "
      echo '🚀 Nginx Starting...' &&
      echo '📋 Config: Landing=https://${SERVER_HOSTNAME}, Toscana=:${TOSCANA_HTTPS_PORT}, Flexora=:${FLEXORA_HTTPS_PORT}' &&

      echo '🔧 Generating nginx configuration...' &&
      cp /etc/nginx/conf.d/default.conf.template /etc/nginx/conf.d/default.conf &&

      echo '🔍 Testing nginx configuration...' &&
      nginx -t &&

      echo '🌐 Starting Nginx...' &&
      nginx -g 'daemon off;'"
    restart: always
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nginx_logs:
    name: nginx_logs
    external: true
  nginx_cache:
    name: nginx_cache
    external: true
